baseURL = "https://karpova-lab.github.io/syringe-pump/"
languageCode = "en-us"
title = "Syringe Pump"
publishDir = "../docs"
theme = "book"
# enableGitInfo = true

[params]
  BookSearch = true
  BookTheme = 'light'
  BookMenuBundle = '/menu'
  BookRepo =  'https://github.com/Karpova-Lab/syringe-pump'
  # BookCommitPath = 'commit'
  # BookEditPath = "edit/main/exampleSite"
  # BookComments = true
  

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4

  [markup.highlight] 
      style = 'friendly'