site_name: Syringe Pump
site_description: Open source syringe pump
site_author: Andy Lustig
repo_url: https://github.com/Karpova-Lab/syringe-pump
repo_name: Karpova-Lab/syringe-pump
edit_uri: ""
docs_dir: src
site_dir: ../docs

theme:
    name: material
    custom_dir: overrides
    icon:
        repo: fontawesome/brands/github
    palette:
        # scheme: slate
        primary: red
        accent: blue
    logo: assets/home.svg
    features:
        - navigation.footer

plugins:
    - git-revision-date-localized
    - search

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - toc:
        title: On this page
        permalink: "#"
        toc_depth: 4

    - admonition
    - pymdownx.highlight
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true

nav:
    - Overview: index.md
    - Mechanics: mechanical.md
    - Electronics: electronics.md
    - Further Resources: further.md

copyright: Copyright &copy; 2023 Andy Lustig
